title: Photo Portfolio
baseurl: "/photos"
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

# Collections
collections:
  photos:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "photos"
    values:
      layout: "gallery"

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md