title: Photo Portfolio
baseurl: "/photos"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown

# Collections
collections:
  works:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md