title: Photo Portfolio
baseurl: "/photos"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown

# Default layout for photo directories
defaults:
  - scope:
      path: "photos"
      type: "pages"
    values:
      layout: "gallery"

# Include photo directories
include:
  - "photos"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md