title: Photo Portfolio
baseurl: "/photos"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown

# Include photo directories and their contents
include:
  - "photos"
  - "photos/*"
  - "photos/**/*"

# Default layout for pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Debug settings
verbose: true